version: '3'

services: 
  portfolio-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=portfolio-db-admin
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - ./mongo_scripts/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - portfolio-db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=portfolio-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=portfolio-db-admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test
